name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          python -m build

      - name: Upload built distributions
        uses: actions/upload-artifact@v4
        with:
          name: package-distributions
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read

    environment:
      name: pypi
      url: https://pypi.org/project/botpapy/

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          password: ${{ secrets.PYPI_API_TOKEN }}

          
